import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Input } from "@chakra-ui/react";
import Contact from "@/components/Home/Contact";
import ScroolProducts from "@/components/ScrollProducts";
import Testimonials from "@/components/Testimonials";
import StorePhoto from "@/components/Home/StorePhoto";
import Annoucements from "@/components/Annoucements";
import { useEffect, useState } from "react";
import { Product } from "@/@types/Product";
import { productProvider } from "@/services/product";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [AllProducts, setAllProducts] = useState<Product[]>([]);
  const [searchProducts, setSearchProducts] = useState<Product[]>([]);
  const [valorInput, setValorInput] = useState("");

  useEffect(() => {
    if (AllProducts.length === 0) {
      const getNewProducts = () => {
        productProvider
          .index()
          .then((response) => setAllProducts(response.data));
      };
      getNewProducts();
    }

    const filteredProducts = AllProducts.filter((product) =>
      product.name.toLowerCase().includes(valorInput.toLowerCase())
    );
    setSearchProducts(filteredProducts);
  }, [AllProducts, valorInput]);

  return (
    <>
      <Head>
        <title>Moveis Eliane</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/moveis.ico" />
      </Head>
      <Header />
      <div className="flex flex-col min-h-screen">
        <main className="flex-1">
          <div className="bg-gray-50 py-16">
            <div className="mx-auto lg:w-3/4 w-full px-16 lg:px-auto flex flex-col gap-7">
              <h2 className="text-2xl text-center">Pesquisar</h2>
              <Input
                type="text"
                value={valorInput}
                onChange={(e) => setValorInput(e.target.value)}
              />
              {valorInput.length <= 0 ? (
                <ScroolProducts
                  title="Todos os móveis!"
                  products={AllProducts}
                />
              ) : (
                <ScroolProducts
                  title="Sua pesquisa!"
                  products={searchProducts}
                />
              )}
            </div>
          </div>
          <Contact />
          <Testimonials />
          <StorePhoto />
          <Annoucements />
        </main>
      </div>
      <Footer />
    </>
  );
}
