import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Button, Text } from "@chakra-ui/react";
import Link from "next/link";
import Contact from "@/components/Home/Contact";
import Card from "@/components/Home/Card";
import ScroolProducts from "@/components/ScrollProducts";
import Testimonials from "@/components/Testimonials";
import StorePhoto from "@/components/Home/StorePhoto";
import Annoucements from "@/components/Annoucements";
import { useEffect, useState } from "react";
import { Product } from "@/@types/Product";
import { productProvider } from "@/services/product";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [AllProducts, setAllProducts] = useState<Product[]>([]);
  const [newProducts, setNewProducts] = useState<Product[]>([]);
  const [usedProducts, setUsedProducts] = useState<Product[]>([]);
  const [balcãoProducts, setBalcãoProducts] = useState<Product[]>([]);
  const [mesaProducts, setMesaProducts] = useState<Product[]>([]);
  const [camaProducts, setCamaProducts] = useState<Product[]>([]);

  useEffect(() => {
    if (AllProducts.length === 0) {
      const getNewProducts = () => {
        productProvider
          .index()
          .then((response) => setAllProducts(response.data));
      };
      getNewProducts();
    }

    if (AllProducts.length > 0) {
      let newProducts = AllProducts.filter(
        (product) => product.state === "novo"
      );
      newProducts.sort(() => Math.random() - 0.5);
      setNewProducts(newProducts);
      let usedProducts = AllProducts.filter(
        (product) => product.state === "usado"
      );
      usedProducts.sort(() => Math.random() - 0.5);
      setUsedProducts(usedProducts);
      let balcãoProducts = AllProducts.filter((product) =>
        product.name.toLowerCase().includes("balcão")
      );
      balcãoProducts.sort(() => Math.random() - 0.5);
      setBalcãoProducts(balcãoProducts);
      let mesaProducts = AllProducts.filter((product) =>
        product.name.toLowerCase().includes("mesa")
      );
      mesaProducts.sort(() => Math.random() - 0.5);

      setMesaProducts(mesaProducts);
      let camaProducts = AllProducts.filter((product) =>
        product.name.toLowerCase().includes("cama")
      );
      camaProducts.sort(() => Math.random() - 0.5);
      setCamaProducts(camaProducts);
    }
  }, [AllProducts]);

  return (
    <>
      <Head>
        <title>Moveis Eliane</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex flex-col min-h-screen">
        <main className="flex-1">
          <Card />
          <div className="bg-gray-50 py-16">
            <div className="mx-auto lg:w-3/4 w-full px-16 lg:px-auto flex flex-col gap-7">
              <ScroolProducts title="Moveis Novos!" products={newProducts} />
              <ScroolProducts title="Moveis Usados!" products={usedProducts} />
              <ScroolProducts
                title="Tudo em Balcão!"
                products={balcãoProducts}
              />
              <ScroolProducts title="Tudo em Mesa!" products={mesaProducts} />
              <ScroolProducts title="Tudo em Cama!" products={camaProducts} />
              <Button className="float-right w-1/2 my-12">
                <Link href="/produtos">Ver todos os produtos</Link>
              </Button>
            </div>
          </div>
          <Contact />
          <Testimonials />
          <StorePhoto />
          <Annoucements />
        </main>
      </div>
      <Footer />
    </>
  );
}
